import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {
  ClerkProvider,
 
} from '@clerk/nextjs'
import Mobilenav from "@/components/mobileMenu";
import Desktop from "@/components/desktopnav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-[#e6e6ff]`}
      >

        <Mobilenav/>
        <Desktop/>

        <main className=" pt-20 container">
        {children}

        </main>
     
      </body>
    </html>
    </ClerkProvider>
  );
}
